In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as skl
import category_encoders as ce   
import shap                     
import xgboost as xgb         
import lightgbm as lgb

In [13]:
d_train = pd.read_csv('datasets/dataset_train.csv')
d_test = pd.read_csv('datasets/dataset_test_X.csv')

In [14]:
#para ver o dataset de treino
d_train

,PID,HHID,WGT,PROXY,REFYEAR,REFMONTH,COUNTRY,NUTS1,REGION,NUTS2_AG,...,IN10,IN11,IN12,IN13,IN14,IN55,IN56,IN57,IN59,IN67
0,1242.0,124201.0,430.632,1.0,2019,10,PT,Continente,Norte,Norte,...,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não
1,8881.0,888102.0,568.249,1.0,2020,1,PT,Continente,Alentejo,Alentejo,...,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não
2,399.0,39902.0,1178.217,1.0,2019,12,PT,Continente,Norte,Norte,...,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Sem resposta,Não aplicável,Não aplicável,40.0,Não aplicável,Sim
3,10589.0,1058901.0,137.602,1.0,2019,11,PT,Continente,Alentejo,Lx V Tejo,...,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não
4,6875.0,687501.0,308.303,1.0,2019,10,PT,Continente,Centro (PT),Lx V Tejo,...,Não,Não aplicável,Não aplicável,Não aplicável,"Doença, exceto doença profissional",Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10957,6998.0,699802.0,2085.914,1.0,2019,11,PT,Continente,Lisboa,Lx V Tejo,...,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Sim
10958,9253.0,925301.0,77.585,1.0,2019,11,PT,Continente,Alentejo,Alentejo,...,Não,Não aplicável,Não aplicável,Não aplicável,"Doença, exceto doença profissional",12.0,25.0,170.0,10.0,Não
10959,7757.0,775702.0,1176.198,1.0,2019,10,PT,Continente,Lisboa,Lx V Tejo,...,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Outro motivo,75.0,96.0,40.0,26.0,Sim
10960,2909.0,290901.0,157.048,1.0,2019,10,PT,Continente,Algarve,Algarve,...,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não
10961,6468.0,646801.0,967.882,1.0,2019,10,PT,Continente,Centro (PT),Lx V Tejo,...,Não aplicável,Não aplicável,Não aplicável,Não aplicável,"Doença, exceto doença profissional",Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não

In [11]:
#para ver o dataset de teste
d_test

,PID,HHID,WGT,PROXY,REFYEAR,REFMONTH,COUNTRY,NUTS1,REGION,NUTS2_AG,...,IN10,IN11,IN12,IN13,IN14,IN55,IN56,IN57,IN59,IN67
0,11334.0,1133401.0,41.589,1.0,2019,10,PT,RA Açores,Região Autónoma dos Açores,RA Açores,...,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,160.0,65.0,50.0,Não aplicável,Não
1,364.0,36401.0,2133.831,1.0,2019,12,PT,Continente,Norte,Norte,...,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não
2,12938.0,1293802.0,154.491,1.0,2019,10,PT,RA Madeira,Região Autónoma da Madeira,RA Madeira,...,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Outro motivo,Não aplicável,Não aplicável,25.0,3.0,Não
3,4550.0,455001.0,679.643,1.0,2019,10,PT,Continente,Centro (PT),Centro,...,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Outro motivo,Sem resposta,Sem resposta,Sem resposta,Não aplicável,Sim
4,9729.0,972902.0,172.019,1.0,2019,12,PT,Continente,Alentejo,Alentejo,...,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3650,10519.0,1051901.0,296.490,1.0,2019,10,PT,Continente,Alentejo,Lx V Tejo,...,Não aplicável,Não aplicável,Não aplicável,Não aplicável,"Acidente de trabalho, excluindo acidente de vi...",100.0,200.0,50.0,Não aplicável,Sim
3651,7048.0,704801.0,458.043,1.0,2019,10,PT,Continente,Lisboa,Lx V Tejo,...,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Outro motivo,30.0,15.0,Não aplicável,Sem resposta,Não
3652,10443.0,1044301.0,153.110,1.0,2019,10,PT,Continente,Alentejo,Lx V Tejo,...,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Sim
3653,11120.0,1112002.0,151.375,1.0,2019,12,PT,RA Açores,Região Autónoma dos Açores,RA Açores,...,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Não aplicável,Sim
3654,7221.0,722101.0,714.155,1.0,2019,11,PT,Continente,Lisboa,Lx V Tejo,...,Sim,Desloca-se em cadeira de rodas,Não aplicável,Não aplicável,"Doença, exceto doença profissional",Não aplicável,Não aplicável,Não aplicável,Não aplicável,Sim